### ISSUE TITLE
Operators are placed wrong

### ISSUE THREAD

**Issue by Maxi1324** [LuckyForce/Logic-Riddle#2]
Dear Logic-Riddle Team,

recently i was using your service. I've tried to solve a normal riddle, llke I always do on my tuesday mornings.
While playing i found a bug!

I've tried to type a expression at the following link 
"https://www.adrian-schauer.at/projects/logic/riddles/riddle/?id=3".
When suddenly I realized there is fundamental bug.
I was shooked!

When i clicked on an operator, the operator is always placed at the end of the Textfield!
But i wanted to place it in the middle.

Can you believe that?
I hope this bug get fixed soon

![image](https://user-images.githubusercontent.com/54480672/162905471-2de41d47-1afd-42b7-93a6-aa2593cd390e.png)

With best regards
your best app tester 
Maximilian Fischer the great

**Comment by LuckyForce** [comment]
Dear Fischer,
we are aware of this "bug" but in the terms of this school project, we decided to let this feature stay like that. But we will ensure you the next time we have some time left we will commit our lives to this problem to guarantee the best user experience for you!
Best regards
Adrian Schauer, in name of the Logic-Riddle Team

**Comment by Maxi1324** [comment]
Dear Mr Schauer,

I understand and respect your point. I am still a bit sad, but that's ok. The reason for that is, that I really enjoy your Project and use it every day. Fortunately the bug won't stop me from using it.
I am really glad, that you'll try to improve yourself on your next Project. I look forward to see it. I've heard it's called Gjokes am I right? I am getting off path. 
At the end, I want to say thank you for the quick responds and i hope, i hear from you in the future, on your next Project :)

With best regards
your best app tester
Maximilian Fischer the great

**Comment by LuckyForce** [comment]
This Issue is now resolved.
