### ISSUE TITLE
Can't create an Account:(

### ISSUE THREAD

**Issue by Maxi1324** [LuckyForce/Logic-Riddle#3]
Dear Logic-Riddle Team,

Recently I've lost my Account credentials.
So I've tried to create a new Account, because i didn't wanted to missout any of those excellent logic Riddles.

Unfortunately this didn't work for me:(
If you don't believe me, look at the following image!
![image](https://user-images.githubusercontent.com/54480672/162907090-e3ee924b-3322-4086-9121-bf3d199efe31.png)

I hope this bug is fixed soon, so i can play those Logic-Riddles again

With best regards
your best app tester
Maximilian Fischer the great

**Comment by LuckyForce** [comment]
The Mailserver was configured wrong because of some service changes. I'll close this Issue now if it still occurs you can still comment below and I'll reopen it.
